export const custromError = {
  ownableUnauthorizedAccount: 'OwnableUnauthorizedAccount',
  newOwnerNotZeroAddress: 'NewOwnerNotZeroAddress',
  erc20TokenNotZeroAddress: 'ERC20TokenNotZeroAddress',
  coldWalletNotZeroAddress: 'ColdWalletNotZeroAddress',
  amountNotZero: 'AmountNotZero',
  timeoutBlocker: 'TimeoutBlocker',
  invalidSignature: 'InvalidSignature',
  usedTransactionId: 'UsedTransactionId',
  contractMustHaveSufficientFunds: 'ContractMustHaveSufficientFunds',
  userMustAllowToUseFunds: 'UserMustAllowToUseFunds',
  userMustHaveFunds: 'UserMustHaveFunds',
  invalidNonce: 'InvalidNonce',
  achievedDepositGoal: 'AchievedDepositGoal',
  achievedWithdrawGoal: 'AchievedWithdrawGoal',
  tooEarly: 'TooEarly',
  tooLate: 'TooLate',
  startDateMustBeGreaterThanCurrentTime: 'StartDateMustBeGreaterThanCurrentTime',
  closeDateMustBeGreaterThanCurrentTime: 'CloseDateMustBeGreaterThanCurrentTime',
  closeDateMustBeGreaterThanStartDate: 'CloseDateMustBeGreaterThanStartDate',
};
