export const customError = {
  ownableUnauthorizedAccount: 'OwnableUnauthorizedAccount',
  ownableInvalidOwner: 'OwnableInvalidOwner',
  erc20TokenNotZeroAddress: 'ERC20TokenNotZeroAddress',
  startDateMustBeGreaterThanCurrentTime: 'StartDateMustBeGreaterThanCurrentTime',
  firstUnlockPercentMustBeLessThanPercentDivider: 'FirstUnlockPercentMustBeLessThanPercentDivider',
  unlockPeriodNotZero: 'UnlockPeriodNotZero',
  unlockPeriodPercentNotZero: 'UnlockPeriodPercentNotZero',
  arrayLengthsNotEqual: 'ArrayLengthsNotEqual',
  accountNotZeroAddress: 'AccountNotZeroAddress',
  accountNotExist: 'AccountNotExist',
  contractMustHaveSufficientFunds: 'ContractMustHaveSufficientFunds',
  cantChangeOngoingVesting: 'CantChangeOngoingVesting',
  nothingToClaim: 'NothingToClaim',
  alreadyClaimed: 'AlreadyClaimed',
  tooLateToRefund: 'TooLateToRefund',
};
